#==============#
# Camera Model #
#==============#

Camera:
# Logitech C270 at 640p, 8/10/24
  name: "Logitech C270 Alejandro"
  setup: "monocular"
  model: "perspective"

  cols: 640
  rows: 480

  fx: 814
  fy: 814
  cx: 303
  cy: 240

  k1: -0.003
  k2: 1.04
  p1: 0.0  
  p2: 0.0
  k3: -3

  fps: 30.0

  color_order: "BGR"

#====================#
# Mapping Parameters #
#====================#

Mapping:

Viewer:

